# 配置数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis_plus?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# 配置mybatisPlus日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #设置mybatis-plus的全局配置
  global-config:
    db-config:
      table-prefix: t_   #表示所有表的前缀为  t_
#      id-type: auto
  #配置类型别名
  type-aliases-package: org.fu.mybatisplus.pojo
  #扫描通用枚举的包
  type-enums-package: org.fu.mybatisplus.enums


  # 注意：mybatis-plus默认将 id作为主键，如果主键不是id，要设置TableId注解
  #  如：在实体类中将 uid作为主键的话，在上面添加@TableId
